use_frameworks!

platform :ios, '9.0'

target 'OINetworking_Example' do
  pod 'OINetworking', :path => '../'

  target 'OINetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
